version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST:-kafka}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      HOSTNAME_COMMAND: ${HOST:-kafka}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_NUM_PARTITIONS: ${PARTITIONS_PER_TOPIC:-4}
    links:
      - zookeeper
  nginx:
      build: ./nginx
      container_name: nginx
      links:
        - broker1:broker1
        - broker2:broker2
        - broker3:broker3
        - broker4:broker4
      ports:
        - "3000:3000"
  internalProxy:
    build: .
    container_name: internalProxy
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
    links:
      - kafka
  externalProxy:
    build: .
    container_name: externalProxy
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
    links:
      - kafka

