version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - shared
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
      - "zookeeper"
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - shared
#  proxynginx:
#    build: ./nginx
#    container_name: proxynginx
#    links:
#      - internalproxy:internalproxy
#      - externalproxy:externalproxy
#    networks:
#      - shared
#    ports:
#      - "3000:3000"
#      - "3001:3001"
#  internalproxy:
#    build: .
#    container_name: internalproxy
#    environment:
#      KAFKA.KAFKA_HOSTS: "kafka:9092"
#      PLUGIN_MANAGER.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
#      PLUGIN_MANAGER.PLUGIN_MANAGEMENT_SERVICE_ENDPOINT: "http://192.168.160.107:8110/dh/rest"
#      PROXY.WEB_SOCKET_SERVER_HOST: "internalproxy"
#      PROXY.ENABLE_PLUGIN_MANAGER: "false"
#      DEBUG: "kafka,pluginmanager"
#    networks:
#      - shared
#  externalproxy:
#    build: .
#    container_name: externalproxy
#    environment:
#      KAFKA.KAFKA_HOSTS: "kafka:9092"
#      PLUGIN_MANAGER.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
#      PLUGIN_MANAGER.PLUGIN_MANAGEMENT_SERVICE_ENDPOINT: "http://192.168.160.107:8110/dh/rest"
#      PROXY.WEB_SOCKET_SERVER_HOST: "externalproxy"
#      PROXY.ENABLE_PLUGIN_MANAGER: "true"
#      DEBUG: "kafka,pluginmanager"
#    networks:
#      - shared
networks:
  shared:
    driver: bridge