version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - shared
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
      - "zookeeper"
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - shared
  proxynginx:
    build: ./nginx
    container_name: proxynginx
    links:
      - internalproxy:internalproxy
      - externalproxy:externalproxy
    networks:
      - shared
    ports:
      - "3000:3000"
      - "3001:3001"
  internalproxy:
    build: .
    container_name: internalproxy
    environment:
      KAFKA.KAFKA_HOSTS: "kafka:9092"
      PROXY.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
      PROXY.WEB_SOCKET_SERVER_HOST: "internalproxy"
      PROXY.ENABLE_PLUGIN_MANGER: "false"
      DEBUG: "kafka,pluginmanager"
    networks:
      - shared
  externalproxy:
    build: .
    container_name: externalproxy
    environment:
      KAFKA.KAFKA_HOSTS: "kafka:9092"
      PROXY.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
      PROXY.WEB_SOCKET_SERVER_HOST: "externalproxy"
      PROXY.ENABLE_PLUGIN_MANGER: "true"
      DEBUG: "kafka,pluginmanager"
    networks:
      - shared
networks:
  shared:
    driver: bridge