version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - shared
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST:-kafka}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    links:
      - zookeeper
    networks:
      - shared
  proxynginx:
      build: ./nginx
      container_name: proxynginx
      links:
        - internalproxy:internalproxy
        - externalproxy:externalproxy
      networks:
        - shared
      ports:
        - "3000:3000"
        - "3001:3001"
  internalproxy:
    build: .
    container_name: internalproxy
    environment:
      KAFKA.KAFKA_HOSTS: "kafka:9092"
      PROXY.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
      PROXY.WEB_SOCKET_SERVER_HOST: "internalproxy"
      PROXY.ENABLE_PLUGIN_MANGER: "false"
      DEBUG: "websocketserver,kafka,messagebuffer,pluginmanager"
    networks:
      - shared
  externalproxy:
    build: .
    container_name: externalproxy
    environment:
      KAFKA.KAFKA_HOSTS: "kafka:9092"
      PROXY.AUTH_SERVICE_ENDPOINT: "http://192.168.160.107:8090/dh/rest"
      PROXY.WEB_SOCKET_SERVER_HOST: "externalproxy"
      PROXY.ENABLE_PLUGIN_MANGER: "true"
      DEBUG: "websocketserver,kafka,messagebuffer,pluginmanager"
    networks:
      - shared
networks:
  shared:
    driver: bridge